import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Providers from './components/Providers'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Top Reads',
  description: 'Generated by create next app',
  icons: {
    icon: ['/square.ico?v=4'],
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-white text-black dark:bg-gray-900 dark:selection:bg-gray-900 dark:text-white h-full selection:bg-gray-50`}>
        <Providers>
          <Navbar />
          <main className='max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 pb-5'>
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
